#!name=Youtube (Music) Enhance
#!desc=Áp dụng cho Youtube & Youtube Music
#!arguments=Chặn nút tải lên:true,Chặn nút lựa chọn:true,Ngôn ngữ dịch phụ đề:zh-Hans,Dịch ngôn ngữ của lời bài hát:zh-Hans,Công cụ thực thi tập lệnh:jsc,Bật chế độ gỡ lỗi:false
#!arguments-desc=- Các thông số che chắn：[true, false] \n- Các thông số dịch thuật：[Mã ngôn ngữ, off] \n- Công cụ kịch bản：[auto, jsc, webview]\n\n1. Mã ngôn ngữ theo sau Google Translate Languages Codes, Khi điền vào off Tắt bản dịch.\n2. Khuyến nghị sử dụng jsc Động cơ，Nhưng bạn vẫn có thể chuyển sang webview Kinh nghiệm Surge Các tính năng mới\n3. Bật chế độ gỡ lỗi để xuất nhiều nhật ký hơn

# > Note
# Youtube Hình ảnh trong hình ảnh và phát lại nền được đóng tương ứng trong máy khách.
#   - Thiết lập -> Tổng quát -> 画中画
#   - Thiết lập -> Phát lại nền và tải xuống -> Chơi trong nền


[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{Công cụ thực thi tập lệnh}}},script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.preview.js
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{Công cụ thực thi tập lệnh}}},script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.preview.js,argument="{"lyricLang":"{{{Dịch ngôn ngữ của lời bài hát}}}","captionLang":"{{{Ngôn ngữ dịch phụ đề}}}","blockUpload":{{{Chặn nút tải lên}}},"blockImmersive":{{{Chặn nút lựa chọn}}},"debug":{{{Bật chế độ gỡ lỗi}}}}"

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data="https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/blank.txt"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
